# Product Requirements Document (PRD) Workflow
name: prd
description: "Scale-adaptive PRD workflow for project levels 2-4. All levels hand off to solutioning workflow (solution-architecture). Automatically adjusts scope based on project complexity. Note: Level 0-1 use tech-spec workflow."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
project_name: "{config_source}:project_name"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
date: system-generated

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/2-plan/prd"

# Instructions - unified for all levels (2-4) with adaptive logic
instructions: "{installed_path}/instructions.md" # Level 2-4 (scale-adaptive)

# Templates
prd_template: "{installed_path}/prd-template.md"
status_template: "{project-root}/bmad/bmm/workflows/_shared/bmm-workflow-status-template.md"
epics_template: "{installed_path}/epics-template.md"

# Output configuration
status_file: "{output_folder}/bmm-workflow-status.md"
default_output_file: "{output_folder}/PRD.md"
epics_output_file: "{output_folder}/epics.md"
validation_output_file: "{output_folder}/PRD-validation-report.md"

# Recommended input documents
recommended_inputs:
  - product_brief: "{output_folder}/product-brief.md"
  - market_research: "{output_folder}/market-research.md"

# Scale parameters - adaptive by project level
scale_parameters:
  level_2: "5-15 stories, 1-2 epics, focused PRD + solutioning handoff"
  level_3: "12-40 stories, 2-5 epics, comprehensive PRD + solutioning handoff"
  level_4: "40+ stories, 5+ epics, enterprise PRD + solutioning handoff"

# Claude Code integration points
claude_code_enhancements:
  - injection_point: "prd-subagents"
  - available_subagents:
      - requirements-analyst: "Requirements analysis and refinement"
      - user-journey-mapper: "User journey and epic boundaries"
      - epic-optimizer: "Epic scope optimization"
      - document-reviewer: "PRD quality validation"

# Workflow configuration
interactive: true # User checkpoints throughout
autonomous: false # Requires user input
allow_parallel: false # Sequential planning process

# Product frameworks available
frameworks:
  - "Jobs-to-be-Done"
  - "User Story Mapping"
  - "Epic Decomposition"
  - "Acceptance Criteria"
  - "MoSCoW Prioritization"

web_bundle:
  name: "prd"
  description: "Scale-adaptive PRD workflow for project levels 2-4. All levels hand off to solutioning workflow (solution-architecture). Automatically adjusts scope based on project complexity. Note: Level 0-1 use tech-spec workflow."
  author: "BMad"
  # Single unified instruction file with adaptive logic
  instructions: "bmad/bmm/workflows/2-plan/prd/instructions.md"
  use_advanced_elicitation: true
  web_bundle_files:
    - "bmad/bmm/workflows/2-plan/prd/instructions.md"
    - "bmad/bmm/workflows/2-plan/prd/prd-template.md"
    - "bmad/bmm/workflows/_shared/bmm-workflow-status-template.md"
    - "bmad/bmm/workflows/2-plan/prd/epics-template.md"
  # Scale parameters - adaptive by project level
  scale_parameters:
    level_2: "5-15 stories, 1-2 epics, focused PRD + solutioning handoff"
    level_3: "12-40 stories, 2-5 epics, comprehensive PRD + solutioning handoff"
    level_4: "40+ stories, 5+ epics, enterprise PRD + solutioning handoff"
  # Product frameworks available
  frameworks:
    - "Jobs-to-be-Done"
    - "User Story Mapping"
    - "Epic Decomposition"
    - "Acceptance Criteria"
    - "MoSCoW Prioritization"
  # Workflow configuration
  interactive: true # User checkpoints throughout
  autonomous: false # Requires user input
  allow_parallel: false # Sequential planning process
