# Test Architect workflow: gate
name: testarch-gate
description: "Quality gate decision for story/epic/release with deterministic PASS/CONCERNS/FAIL/WAIVED status"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/testarch/gate"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
template: "{installed_path}/gate-template.md"

# Variables and inputs
variables:
  # Gate target
  gate_type: "story" # story, epic, release, hotfix
  story_id: "" # e.g., "1.3" for story mode
  epic_num: "" # e.g., "1" for epic mode
  release_version: "" # e.g., "v2.4.0" for release mode

  # Gate decision configuration
  decision_mode: "deterministic" # deterministic (rule-based) or manual (team decision)
  allow_waivers: true # Allow business-approved waivers for FAIL → WAIVED
  require_evidence: true # Require links to test results, reports, etc.

  # Input sources (auto-discover if not provided)
  story_file: "" # Path to story markdown
  test_design_file: "" # Path to test-design.md (risk assessment)
  trace_file: "" # Path to traceability-matrix.md (coverage)
  nfr_file: "" # Path to nfr-assessment.md (non-functional validation)
  test_results: "" # Path to test execution results (CI artifacts, reports)

  # Decision criteria (thresholds)
  min_p0_pass_rate: 100 # P0 tests must have 100% pass rate
  min_p1_pass_rate: 95 # P1 tests threshold
  min_overall_pass_rate: 90 # Overall test pass rate
  min_coverage: 80 # Code/requirement coverage minimum
  max_critical_nfrs_fail: 0 # No critical NFRs can fail
  max_security_issues: 0 # No unresolved security issues

  # Risk tolerance
  allow_p2_failures: true # P2 failures don't block release
  allow_p3_failures: true # P3 failures don't block release
  escalate_p1_failures: true # P1 failures require escalation approval

  # Output configuration
  output_file: "{output_folder}/gate-decision-{gate_type}-{story_id}{epic_num}{release_version}.md"
  append_to_history: true # Append to bmm-workflow-status.md gate history
  notify_stakeholders: true # Generate notification message for team

  # Advanced options
  auto_load_knowledge: true # Load risk-governance, probability-impact, test-quality fragments
  check_all_workflows_complete: true # Verify test-design, trace, nfr-assess are complete
  validate_evidence_freshness: true # Warn if assessments are >7 days old
  require_sign_off: false # Require named approver for gate decision

# Output configuration
default_output_file: "{output_folder}/gate-decision.md"

# Required tools
required_tools:
  - read_file # Read story, assessments, test results
  - write_file # Create gate decision document
  - search_repo # Find related artifacts
  - list_files # Discover assessments

# Recommended inputs
recommended_inputs:
  - story: "Story or epic being gated (required)"
  - test_design: "Risk assessment with P0-P3 prioritization (required)"
  - trace: "Requirements-to-tests traceability matrix (required)"
  - nfr_assess: "Non-functional requirements validation (recommended)"
  - test_results: "CI/CD test execution results (required)"
  - code_coverage: "Code coverage report (recommended)"

tags:
  - qa
  - gate
  - test-architect
  - release
  - decision

execution_hints:
  interactive: false # Minimize prompts
  autonomous: true # Proceed without user input unless blocked
  iterative: false # Gate decision is single-pass

web_bundle: false
