# BMAD™ Method Core Configuration

code: bmb
name: "BMB: BMad Builder - Agent, Workflow and Module Builder"
default_selected: false # This module will not be selected by default for new installations

prompt: "Happy Building - Build the Modules, Workflows and Agents of your dreams."
# Variables from Core Config inserted:
## user_name
## communication_language
## output_folder
